### ISSUE TITLE
annotator

### ISSUE THREAD

**Issue by bittlingmayer** [fastent/fastent#2]
Given an unlabelled corpus, and lists of named entities (one list per entity type), create a labelled corpus.

Something like this:

```
import fastent

fastent.io(corpus, "universities.txt", "persons.txt", "companies.txt")
```

Should corpus be a text file, a zip file, a dir, a path to an S3 bucket?

**Comment by osoblanco** [comment]
Can I assume that the unlabeled corpus is composed of the entities in the lists?

**Comment by osoblanco** [comment]
Although the syntax now is different isn't the issue effectively closed?
